### ISSUE TITLE
Upload to chrome web store?

### ISSUE THREAD

**Issue by nermin99** [areknawo/BetterConsole#1]
Hi! Would you mind making the extension available on the chrome web store? :) <3

**Comment by areknawo** [comment]
The non-public beta version is available here:
https://chrome.google.com/webstore/detail/betterconsole-beta/bhlbffgngnjfleeaiaoojhfhbdhijfep?hl=pl&authuser=0

If you want to play with the code I encourage you to do one of the following:
- If only for personal use - just ZIP the build and use that as a development extension to play with BC;
- If you want to publish yourself - you've got all the rights to do so;
- If you want to PR the changes - I'm all for it, although I don't actively work on this project.

Keep in mind any update to the current beta package or publication of a new one to CWS, will likely require transitioning to manifest v3.
